// packages/vue/src/components/Card.vue
<script setup lang="ts">
/**
 * Card — generic bordered container. Same chrome as TerminalFrame
 * minus the inset title. Pass @click to render as a button.
 */
interface Props {
  accent?: 'neutral' | 'info' | 'success' | 'warning' | 'danger';
  surface?: 'flat' | 'elevated';
  padding?: 'none' | 'sm' | 'md' | 'lg';
  ariaLabel?: string;
  /** When true, renders as a <button> regardless of parent listener. */
  clickable?: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  accent: 'neutral',
  surface: 'flat',
  padding: 'md',
  clickable: false,
});
const emit = defineEmits<{ click: [event: MouseEvent] }>();
</script>

<template>
  <button
    v-if="props.clickable"
    type="button"
    class="cathode-card is-clickable"
    :data-accent="props.accent"
    :data-surface="props.surface"
    :data-padding="props.padding"
    :aria-label="props.ariaLabel"
    @click="(e) => emit('click', e)"
  >
    <slot />
  </button>
  <div
    v-else
    class="cathode-card"
    :data-accent="props.accent"
    :data-surface="props.surface"
    :data-padding="props.padding"
    :aria-label="props.ariaLabel"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/Card.tsx
import type { ReactNode } from 'react';

/**
 * Card — generic bordered container. Same chrome as TerminalFrame but
 * without the inset title, so it composes as a panel for arbitrary
 * content (readouts, forms, info blocks, etc.). Use TerminalFrame when
 * you want a labelled group; use Card when the content is self-
 * explanatory or you want to place your own heading inside.
 *
 * The optional `accent` shifts the border to a semantic color — pass
 * `"danger"` for warning/error zones, `"info"` to draw attention, etc.
 * `elevated` uses the panel background; `flat` keeps the bg transparent
 * so the card sits on the page surface.
 */
export interface CardProps {
  children: ReactNode;
  accent?: 'neutral' | 'info' | 'success' | 'warning' | 'danger';
  /** Fill behavior. `elevated` uses panel bg, `flat` is transparent. Default `flat`. */
  surface?: 'flat' | 'elevated';
  /** Padding preset. Default `md`. */
  padding?: 'none' | 'sm' | 'md' | 'lg';
  /** Render as a button — fires `onClick` and picks up focus/hover styling. */
  onClick?: () => void;
  className?: string;
  'aria-label'?: string;
}

export function Card({
  children,
  accent = 'neutral',
  surface = 'flat',
  padding = 'md',
  onClick,
  className,
  'aria-label': ariaLabel,
}: CardProps) {
  const classes = [
    'cathode-card',
    onClick ? 'is-clickable' : '',
    className,
  ].filter(Boolean).join(' ');

  const props = {
    className: classes,
    'data-accent': accent,
    'data-surface': surface,
    'data-padding': padding,
  };

  if (onClick) {
    return (
      <button type="button" onClick={onClick} aria-label={ariaLabel} {...props}>
        {children}
      </button>
    );
  }

  return <div {...props} aria-label={ariaLabel}>{children}</div>;
}
