// packages/vue/src/components/Chips.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCathode } from '../useCathode';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

export interface Chip {
  label: string;
  value?: string;
  disabled?: boolean;
}

interface Props {
  /** Flat list or array-of-arrays for grouped layouts. */
  groups: Chip[] | Chip[][];
}
const props = defineProps<Props>();
const emit = defineEmits<{ select: [chip: Chip] }>();
const cathode = useCathode();

const grouped = computed<Chip[][]>(() =>
  Array.isArray(props.groups[0]) ? (props.groups as Chip[][]) : [props.groups as Chip[]],
);

function handle(chip: Chip) {
  if (chip.disabled) return;
  if (cathode.haptic) haptic('tap');
  if (cathode.sound)  sound('click', { enabled: true });
  emit('select', chip);
}
</script>

<template>
  <div class="cathode-chips">
    <div
      v-for="(group, gi) in grouped"
      :key="gi"
      class="cathode-chips-group"
    >
      <button
        v-for="chip in group"
        :key="chip.label"
        type="button"
        class="cathode-chip"
        :data-motion="cathode.motion"
        :disabled="chip.disabled"
        @click="handle(chip)"
      >{{ chip.label }}</button>
      <span v-if="gi < grouped.length - 1" class="cathode-chips-divider" aria-hidden="true" />
    </div>
  </div>
</template>

<style scoped>
button[data-motion='strong']:active:not(:disabled) { transform: scale(0.97); }
button[data-motion='subtle']:active:not(:disabled) { transform: scale(0.99); }
button { transition: transform 80ms cubic-bezier(0.4, 0, 0.2, 1); }
</style>

// packages/react/src/components/Chips.tsx
import { motion } from 'framer-motion';
import { useCathode } from '../CathodeProvider';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

/**
 * Horizontally scrolling row of tappable preset chips. Whichever chip
 * the user taps fires `onSelect(item)` — useful for "insert this
 * phrase into the composer" or "apply this filter" patterns.
 *
 * Groups are optional. When provided, a thin vertical divider is
 * rendered between them. Useful for clustering semantically related
 * chips (e.g. `Emergency | Everyday | Status`).
 *
 * Chips are pure triggers, not toggles — state lives in the parent.
 * If you need on/off chips, wrap your own with `Toggle` behind them.
 */
export interface Chip {
  /** Displayed text. */
  label: string;
  /** Optional value returned to `onSelect`. Defaults to `label`. */
  value?: string;
  /** Disable this specific chip. */
  disabled?: boolean;
}

export interface ChipsProps {
  /** Flat list or array-of-arrays for grouped layouts. */
  groups: Chip[] | Chip[][];
  onSelect: (chip: Chip) => void;
  className?: string;
}

export function Chips({ groups, onSelect, className }: ChipsProps) {
  const { motion: motionIntensity, haptic: hapticOn, sound: soundOn } = useCathode();
  const whileTap = motionIntensity === 'none' ? {} :
    { scale: motionIntensity === 'subtle' ? 0.99 : 0.97 };

  // Normalize to grouped form so the render path is one code path.
  const isGrouped = Array.isArray(groups[0]);
  const grouped: Chip[][] = isGrouped ? (groups as Chip[][]) : [groups as Chip[]];

  const handle = (chip: Chip) => {
    if (chip.disabled) return;
    if (hapticOn) haptic('tap');
    if (soundOn) sound('click', { enabled: true });
    onSelect(chip);
  };

  return (
    <div className={['cathode-chips', className].filter(Boolean).join(' ')}>
      {grouped.map((group, gi) => (
        <div key={gi} className="cathode-chips-group">
          {group.map((chip) => (
            <motion.button
              key={chip.label}
              type="button"
              className="cathode-chip"
              onClick={() => handle(chip)}
              disabled={chip.disabled}
              whileTap={chip.disabled ? undefined : whileTap}
            >
              {chip.label}
            </motion.button>
          ))}
          {gi < grouped.length - 1 ? <span className="cathode-chips-divider" aria-hidden /> : null}
        </div>
      ))}
    </div>
  );
}
