// packages/vue/src/components/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue';

interface Props {
  modelValue: number;
  totalPages: number;
  ariaLabel?: string;
}
const props = withDefaults(defineProps<Props>(), { ariaLabel: 'Pagination' });
const emit = defineEmits<{ 'update:modelValue': [page: number] }>();

type Token = number | '…';
function windowedPages(page: number, total: number): Token[] {
  const result: Token[] = [];
  const start = Math.max(2, page - 1);
  const end = Math.min(total - 1, page + 1);
  result.push(1);
  if (start > 2) result.push('…');
  for (let p = start; p <= end; p++) result.push(p);
  if (end < total - 1) result.push('…');
  if (total > 1) result.push(total);
  return result;
}

const pages = computed(() => windowedPages(props.modelValue, props.totalPages));

function go(n: number) {
  const clamped = Math.max(1, Math.min(props.totalPages, n));
  if (clamped !== props.modelValue) emit('update:modelValue', clamped);
}
</script>

<template>
  <nav v-if="props.totalPages > 1" class="cathode-pagination" :aria-label="props.ariaLabel">
    <button
      type="button"
      class="cathode-pagination-arrow"
      :disabled="props.modelValue <= 1"
      aria-label="Previous page"
      @click="go(props.modelValue - 1)"
    >‹</button>
    <template v-for="(p, i) in pages" :key="i">
      <span v-if="p === '…'" class="cathode-pagination-gap" aria-hidden="true">…</span>
      <button
        v-else
        type="button"
        class="cathode-pagination-page"
        :data-on="p === props.modelValue ? 'true' : 'false'"
        :aria-label="`Page ${p}`"
        :aria-current="p === props.modelValue ? 'page' : undefined"
        @click="go(p as number)"
      >{{ p }}</button>
    </template>
    <button
      type="button"
      class="cathode-pagination-arrow"
      :disabled="props.modelValue >= props.totalPages"
      aria-label="Next page"
      @click="go(props.modelValue + 1)"
    >›</button>
  </nav>
</template>

// packages/react/src/components/Pagination.tsx
/**
 * Pagination — page-jumping control for lists that span multiple pages.
 * Renders prev/next arrows + a windowed set of page buttons around the
 * current page. Controlled: the caller owns `page` and passes an
 * `onChange` handler.
 *
 * Window size is fixed at 5 (2 before + current + 2 after, clipped at
 * the edges). Edge ellipses indicate skipped ranges.
 */
export interface PaginationProps {
  /** 1-based current page. */
  page: number;
  /** Total number of pages. 0 or 1 → component renders nothing. */
  totalPages: number;
  onChange: (page: number) => void;
  className?: string;
  'aria-label'?: string;
}

export function Pagination({ page, totalPages, onChange, className, 'aria-label': ariaLabel = 'Pagination' }: PaginationProps) {
  if (totalPages <= 1) return null;

  const go = (n: number) => {
    const clamped = Math.max(1, Math.min(totalPages, n));
    if (clamped !== page) onChange(clamped);
  };

  const pages = windowedPages(page, totalPages);

  return (
    <nav className={['cathode-pagination', className].filter(Boolean).join(' ')} aria-label={ariaLabel}>
      <button
        type="button"
        className="cathode-pagination-arrow"
        onClick={() => go(page - 1)}
        disabled={page <= 1}
        aria-label="Previous page"
      >
        ‹
      </button>
      {pages.map((p, i) =>
        p === '…' ? (
          <span key={`gap-${i}`} className="cathode-pagination-gap" aria-hidden>…</span>
        ) : (
          <button
            key={p}
            type="button"
            className="cathode-pagination-page"
            data-on={p === page ? 'true' : 'false'}
            onClick={() => go(p)}
            aria-label={`Page ${p}`}
            aria-current={p === page ? 'page' : undefined}
          >
            {p}
          </button>
        )
      )}
      <button
        type="button"
        className="cathode-pagination-arrow"
        onClick={() => go(page + 1)}
        disabled={page >= totalPages}
        aria-label="Next page"
      >
        ›
      </button>
    </nav>
  );
}

type Token = number | '…';

function windowedPages(page: number, total: number): Token[] {
  // 5-wide window around the current page, with ellipsis markers
  // showing that the 1/total edges are reachable.
  const result: Token[] = [];
  const start = Math.max(2, page - 1);
  const end = Math.min(total - 1, page + 1);
  result.push(1);
  if (start > 2) result.push('…');
  for (let p = start; p <= end; p++) result.push(p);
  if (end < total - 1) result.push('…');
  if (total > 1) result.push(total);
  return result;
}
