// packages/vue/src/components/PulsingDot.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

/** Pulsing square — pure CSS keyframes, no framer-motion dep. */
interface Props {
  color?: string;
  size?: number;
}
const props = withDefaults(defineProps<Props>(), { size: 8 });
const style = computed<CSSProperties>(() => ({
  width: `${props.size}px`,
  height: `${props.size}px`,
  color: props.color,
}));
</script>

<template>
  <span class="cathode-pulsingdot" :style="style" aria-hidden="true" />
</template>

// packages/react/src/components/PulsingDot.tsx
/**
 * Small square that pulses in place to signal "something is happening"
 * without a full progress indicator. Animation is pure CSS
 * (@keyframes cathode-pulse) — no framer-motion overhead for this
 * simple a case. Respects `prefers-reduced-motion` automatically.
 */
export interface PulsingDotProps {
  /** CSS color — defaults to current text color via `currentColor`. */
  color?: string;
  /** Edge size in px. Default 8. */
  size?: number;
  className?: string;
}

export function PulsingDot({ color, size = 8, className }: PulsingDotProps) {
  return (
    <span
      className={['cathode-pulsingdot', className].filter(Boolean).join(' ')}
      style={{
        width: size,
        height: size,
        color: color,
      }}
      aria-hidden
    />
  );
}
