// packages/vue/src/components/ScanLine.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

/** Decorative CRT overlay — scan grid + sweeping beam. */
interface Props {
  speed?: number;
  color?: string;
  patternOpacity?: number;
}
const props = withDefaults(defineProps<Props>(), {
  speed: 4,
  patternOpacity: 0.06,
});
const style = computed<CSSProperties>(() => ({
  ['--cathode-scanline-speed' as any]: `${props.speed}s`,
  ['--cathode-scanline-color' as any]:
    props.color ?? 'color-mix(in srgb, var(--cathode-color-info) 60%, transparent)',
  ['--cathode-scanline-pattern-opacity' as any]: props.patternOpacity,
}));
</script>

<template>
  <span class="cathode-scanline" :style="style">
    <slot />
    <span class="cathode-scanline-grid" aria-hidden="true" />
    <span class="cathode-scanline-beam" aria-hidden="true" />
  </span>
</template>

// packages/react/src/components/ScanLine.tsx
import type { ReactNode } from 'react';

/**
 * ScanLine — decorative CRT-era overlay. Renders two thin lines and a
 * scanning beam that sweeps top-to-bottom, layered over children.
 * Pairs well with TerminalFrame / Card for that "vintage display"
 * feel without harming legibility.
 *
 * Purely decorative — `aria-hidden` by default. Respects
 * `prefers-reduced-motion` via the base CSS.
 */
export interface ScanLineProps {
  children?: ReactNode;
  /** Sweep duration, seconds. Default 4. */
  speed?: number;
  /** Sweep line color. Defaults to semi-transparent info. */
  color?: string;
  /** Horizontal scanline pattern opacity 0–1. Default 0.06. */
  patternOpacity?: number;
  className?: string;
}

export function ScanLine({
  children,
  speed = 4,
  color,
  patternOpacity = 0.06,
  className,
}: ScanLineProps) {
  const style: React.CSSProperties = {
    ['--cathode-scanline-speed' as string]: `${speed}s`,
    ['--cathode-scanline-color' as string]: color ?? 'color-mix(in srgb, var(--cathode-color-info) 60%, transparent)',
    ['--cathode-scanline-pattern-opacity' as string]: patternOpacity,
  };
  return (
    <span className={['cathode-scanline', className].filter(Boolean).join(' ')} style={style}>
      {children}
      <span className="cathode-scanline-grid" aria-hidden />
      <span className="cathode-scanline-beam" aria-hidden />
    </span>
  );
}
