// packages/vue/src/components/TextField.vue
<script setup lang="ts">
import { ref, watch, onUnmounted, inject } from 'vue';
import { useCathode } from '../useCathode';
import type { CathodeAIProvider } from '../ai/provider';
import { FORM_FIELD_KEY } from './formFieldContext';

/** Opt-in AI suggest config. Matches TextField's shape in @cathode-ui/react. */
export interface TextFieldAIConfig {
  suggest: boolean;
  provider?: CathodeAIProvider;
  debounceMs?: number;
}

interface Props {
  modelValue: string;
  placeholder?: string;
  disabled?: boolean;
  ai?: TextFieldAIConfig;
  weight?: 'regular' | 'bold';
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
}
const props = withDefaults(defineProps<Props>(), { weight: 'regular' });
const emit = defineEmits<{ 'update:modelValue': [v: string] }>();

const cathode = useCathode();
const formField = inject(FORM_FIELD_KEY, undefined);
const suggestion = ref('');
let abort: AbortController | null = null;
let timer: ReturnType<typeof setTimeout> | null = null;

watch(
  () => [props.modelValue, props.ai?.suggest, props.ai?.debounceMs, props.ai?.provider],
  () => {
    if (timer) clearTimeout(timer);
    const provider = props.ai?.provider ?? cathode.ai;
    abort?.abort();
    suggestion.value = '';
    if (!props.ai?.suggest || !provider || !props.modelValue) return;
    const delay = props.ai.debounceMs ?? 200;
    timer = setTimeout(async () => {
      const ctrl = new AbortController();
      abort = ctrl;
      let acc = '';
      try {
        for await (const chunk of provider.suggest(props.modelValue, ctrl.signal)) {
          if (ctrl.signal.aborted) return;
          acc += chunk;
          suggestion.value = acc;
        }
      } catch { /* silent */ }
    }, delay);
  },
  { immediate: true },
);
onUnmounted(() => {
  if (timer) clearTimeout(timer);
  abort?.abort();
});

function onInput(e: Event) {
  emit('update:modelValue', (e.target as HTMLInputElement).value);
}
function onKey(e: KeyboardEvent) {
  if (e.key === 'Tab' && suggestion.value) {
    e.preventDefault();
    emit('update:modelValue', props.modelValue + suggestion.value);
    suggestion.value = '';
  }
}
</script>

<template>
  <div class="cathode-textfield" :data-weight="props.weight">
    <input
      type="text"
      class="cathode-textfield-input"
      :value="props.modelValue"
      :placeholder="props.placeholder"
      :disabled="props.disabled"
      :aria-label="(props.ariaLabelledby || formField?.labelledBy) ? undefined : props.ariaLabel"
      :aria-labelledby="props.ariaLabelledby ?? formField?.labelledBy"
      :aria-describedby="props.ariaDescribedby ?? formField?.describedBy"
      autocomplete="off"
      spellcheck="false"
      @input="onInput"
      @keydown="onKey"
    />
    <div v-if="suggestion" class="cathode-textfield-suggest" aria-hidden="true">
      <span style="opacity: 0">{{ props.modelValue }}</span>{{ suggestion }}
    </div>
  </div>
</template>

// packages/react/src/components/TextField.tsx
import { useEffect, useRef, useState } from 'react';
import type { KeyboardEvent } from 'react';
import { useCathode } from '../CathodeProvider';
import type { CathodeAIProvider } from '../ai/provider';

/**
 * Monospace text input. Ghost-text AI suggestion is opt-in via
 * `ai={{ suggest: true }}`; otherwise it's a plain field.
 *
 * Suggest behavior:
 *   - While the user is typing, we debounce (200ms), then stream the
 *     first chunk of `provider.suggest(prefix)` as ghost text behind
 *     the caret. Subsequent keystrokes cancel the in-flight stream.
 *   - Pressing `Tab` accepts the suggestion (appends to value).
 *   - Any other keypress discards it.
 *
 * The AbortController-per-request pattern ensures we never leak a
 * streaming request from a stale prefix.
 */
export interface TextFieldAIConfig {
  suggest: boolean;
  /** Override the provider from CathodeProvider. */
  provider?: CathodeAIProvider;
  /** Debounce before firing suggest (ms). Default 200. */
  debounceMs?: number;
}

export interface TextFieldProps {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  disabled?: boolean;
  ai?: TextFieldAIConfig;
  /** Font weight of the typed text. Default 'regular'. */
  weight?: 'regular' | 'bold';
  className?: string;
  'aria-label'?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
}

export function TextField({
  value,
  onChange,
  placeholder,
  disabled,
  ai,
  weight = 'regular',
  className,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  'aria-describedby': ariaDescribedBy,
}: TextFieldProps) {
  const { ai: globalAI } = useCathode();
  const provider = ai?.provider ?? globalAI;
  const [suggestion, setSuggestion] = useState<string>('');
  const abortRef = useRef<AbortController | null>(null);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Any change invalidates the prior suggestion + in-flight request.
  useEffect(() => {
    if (!ai?.suggest || !provider) return;
    abortRef.current?.abort();
    setSuggestion('');
    if (!value) return;
    if (debounceRef.current) clearTimeout(debounceRef.current);
    const delay = ai.debounceMs ?? 200;
    debounceRef.current = setTimeout(() => {
      run();
    }, delay);
    return () => { if (debounceRef.current) clearTimeout(debounceRef.current); };

    async function run() {
      const ctrl = new AbortController();
      abortRef.current = ctrl;
      try {
        let acc = '';
        for await (const chunk of provider!.suggest(value, ctrl.signal)) {
          if (ctrl.signal.aborted) return;
          acc += chunk;
          setSuggestion(acc);
        }
      } catch {
        // Provider failures just leave the suggestion empty. The main
        // input keeps working — suggestion is a nice-to-have.
      }
    }
  }, [value, ai?.suggest, ai?.debounceMs, provider]);

  const onKey = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Tab' && suggestion) {
      e.preventDefault();
      onChange(value + suggestion);
      setSuggestion('');
    }
  };

  return (
    <div className={['cathode-textfield', className].filter(Boolean).join(' ')} data-weight={weight}>
      <input
        type="text"
        className="cathode-textfield-input"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={onKey}
        placeholder={placeholder}
        disabled={disabled}
        aria-label={ariaLabelledBy ? undefined : ariaLabel}
        aria-labelledby={ariaLabelledBy}
        aria-describedby={ariaDescribedBy}
        autoComplete="off"
        spellCheck={false}
      />
      {suggestion ? (
        <div className="cathode-textfield-suggest" aria-hidden>
          <span style={{ opacity: 0 }}>{value}</span>
          {suggestion}
        </div>
      ) : null}
    </div>
  );
}
