// packages/react/src/components/ActivityBar.tsx
import { useCathode } from '../CathodeProvider';

/**
 * Pseudo-random "activity" meter — same pixel cells as `PixelBar` but
 * each cell flickers based on a deterministic seed rather than a
 * level value. Gives the VU-meter look of a transmitting walkie or
 * a speech-synth talking head without actually analyzing a signal.
 *
 * Pattern intensity (`0…1`) controls the probability of any given
 * cell being lit. `0` = all cells dim; `1` = all cells lit. The
 * sequence is deterministic per-seed so parent components can drive
 * animation by bumping a seed value on a tick.
 */
export interface ActivityBarProps {
  /** Probability a given cell is lit. Clamped to [0, 1]. */
  intensity: number;
  /** Deterministic RNG seed. Advance externally to animate. */
  seed?: number;
  cells?: number;
  fill?: string;
  cellSize?: number;
  className?: string;
}

export function ActivityBar({
  intensity,
  seed = 0,
  cells = 24,
  fill,
  cellSize = 6,
  className,
}: ActivityBarProps) {
  useCathode(); // subscribe (currently unused, reserved for motion intensity)
  const clamped = Math.max(0, Math.min(1, intensity));

  return (
    <div
      className={['cathode-pixelbar', className].filter(Boolean).join(' ')}
      role="presentation"
      style={fill ? ({ ['--cathode-pixelbar-fill']: fill } as React.CSSProperties) : undefined}
    >
      {Array.from({ length: cells }, (_, i) => (
        <span
          key={i}
          className="cathode-pixelbar-cell"
          data-lit={isLit(i, seed, clamped) ? 'true' : 'false'}
          style={{ width: cellSize, height: cellSize }}
        />
      ))}
    </div>
  );
}

/** Deterministic pseudo-random bit for (cell, seed) pair. The shared
 * algorithm keeps visuals consistent across platforms + frameworks. */
function isLit(cell: number, seed: number, intensity: number): boolean {
  // Knuth multiplicative hash for cheap, decent scatter.
  const h = (Math.imul(seed, 2654435761) ^ Math.imul(cell, 11)) >>> 0;
  return (h & 0xff) / 255 < intensity;
}

// packages/vue/src/components/ActivityBar.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

/**
 * Pseudo-random "activity" meter. Same pixel cells as PixelBar,
 * lit by a deterministic seed rather than a level value.
 */
interface Props {
  intensity: number;
  seed?: number;
  cells?: number;
  fill?: string;
  cellSize?: number;
}
const props = withDefaults(defineProps<Props>(), {
  seed: 0,
  cells: 24,
  cellSize: 6,
});

const clamped = computed(() => Math.max(0, Math.min(1, props.intensity)));

function isLit(cell: number, seed: number, intensity: number): boolean {
  const h = (Math.imul(seed, 2654435761) ^ Math.imul(cell, 11)) >>> 0;
  return (h & 0xff) / 255 < intensity;
}

const rootStyle = computed<CSSProperties>(() =>
  props.fill ? ({ ['--cathode-pixelbar-fill' as any]: props.fill }) : ({}),
);
</script>

<template>
  <div class="cathode-pixelbar" role="presentation" :style="rootStyle">
    <span
      v-for="i in props.cells"
      :key="i"
      class="cathode-pixelbar-cell"
      :data-lit="isLit(i - 1, props.seed, clamped) ? 'true' : 'false'"
      :style="{ width: `${props.cellSize}px`, height: `${props.cellSize}px` }"
    />
  </div>
</template>
