// packages/react/src/components/Breadcrumbs.tsx
/**
 * Breadcrumbs — path-style navigation row. The last item is treated
 * as the current location (rendered as static text, not a link) and
 * marked with `aria-current="page"`.
 *
 * Separator defaults to "›" which matches the terminal aesthetic
 * and avoids the cramped "/" slash.
 */
export interface BreadcrumbItem {
  label: string;
  href?: string;
}

export interface BreadcrumbsProps {
  items: ReadonlyArray<BreadcrumbItem>;
  separator?: string;
  className?: string;
  'aria-label'?: string;
}

export function Breadcrumbs({
  items,
  separator = '›',
  className,
  'aria-label': ariaLabel = 'Breadcrumb',
}: BreadcrumbsProps) {
  return (
    <nav className={['cathode-breadcrumbs', className].filter(Boolean).join(' ')} aria-label={ariaLabel}>
      <ol className="cathode-breadcrumbs-list">
        {items.map((item, i) => {
          const isLast = i === items.length - 1;
          return (
            <li key={i} className="cathode-breadcrumbs-item">
              {item.href && !isLast ? (
                <a className="cathode-breadcrumbs-link" href={item.href}>{item.label}</a>
              ) : (
                <span
                  className="cathode-breadcrumbs-current"
                  aria-current={isLast ? 'page' : undefined}
                >
                  {item.label}
                </span>
              )}
              {!isLast ? (
                <span className="cathode-breadcrumbs-sep" aria-hidden>{separator}</span>
              ) : null}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}

// packages/vue/src/components/Breadcrumbs.vue
<script setup lang="ts">
export interface BreadcrumbItem {
  label: string;
  href?: string;
}

interface Props {
  items: readonly BreadcrumbItem[];
  separator?: string;
  ariaLabel?: string;
}
const props = withDefaults(defineProps<Props>(), { separator: '›', ariaLabel: 'Breadcrumb' });
</script>

<template>
  <nav class="cathode-breadcrumbs" :aria-label="props.ariaLabel">
    <ol class="cathode-breadcrumbs-list">
      <li
        v-for="(item, i) in props.items"
        :key="i"
        class="cathode-breadcrumbs-item"
      >
        <a
          v-if="item.href && i !== props.items.length - 1"
          class="cathode-breadcrumbs-link"
          :href="item.href"
        >{{ item.label }}</a>
        <span
          v-else
          class="cathode-breadcrumbs-current"
          :aria-current="i === props.items.length - 1 ? 'page' : undefined"
        >{{ item.label }}</span>
        <span
          v-if="i !== props.items.length - 1"
          class="cathode-breadcrumbs-sep"
          aria-hidden="true"
        >{{ props.separator }}</span>
      </li>
    </ol>
  </nav>
</template>
