// packages/react/src/components/Counter.tsx
import { motion } from 'framer-motion';
import { useCathode } from '../CathodeProvider';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

/**
 * Numeric rocker — `[−]  LABEL VALUE  [+]`. Replaces the generic HTML
 * `<input type="number">` (bad on mobile) and the SwiftUI-style layout
 * where +/- buttons are detached from their label.
 *
 * Here the label + current value are welded into the same bordered
 * container as the two buttons, which reads as one control. Ideal for
 * values the user nudges frequently (volume, speed, count).
 *
 * Feedback: `tick` sound + `tap` haptic on every step. At the edges
 * (min reached / max reached) the button dims; no feedback fires.
 */
export interface CounterProps {
  value: number;
  onChange: (v: number) => void;
  min?: number;
  max?: number;
  step?: number;
  /** Caption shown before the value, e.g. "WPM". Optional. */
  label?: string;
  /** Formatter for the shown value. Default: `String`. */
  format?: (v: number) => string;
  disabled?: boolean;
  className?: string;
}

export function Counter({
  value,
  onChange,
  min = 0,
  max = 100,
  step = 1,
  label,
  format,
  disabled,
  className,
}: CounterProps) {
  const { motion: motionIntensity, haptic: hapticOn, sound: soundOn } = useCathode();

  const canDec = !disabled && value - step >= min;
  const canInc = !disabled && value + step <= max;
  const fmt = format ?? String;

  const fire = (direction: -1 | 1) => {
    const next = value + direction * step;
    if (next < min || next > max) return;
    if (hapticOn) haptic('tap');
    if (soundOn) sound('tick', { enabled: true });
    onChange(next);
  };

  const whileTap = motionIntensity === 'none' ? {} :
    { scale: motionIntensity === 'subtle' ? 0.99 : 0.97 };

  return (
    <div className={['cathode-counter', className].filter(Boolean).join(' ')}>
      <motion.button
        type="button"
        className="cathode-counter-btn"
        onClick={() => fire(-1)}
        disabled={!canDec}
        whileTap={canDec ? whileTap : undefined}
        aria-label="Decrease"
      >
        −
      </motion.button>
      <div className="cathode-counter-display">
        {label ? <span className="cathode-counter-label">{label}</span> : null}
        <span className="cathode-counter-value">{fmt(value)}</span>
      </div>
      <motion.button
        type="button"
        className="cathode-counter-btn"
        onClick={() => fire(1)}
        disabled={!canInc}
        whileTap={canInc ? whileTap : undefined}
        aria-label="Increase"
      >
        +
      </motion.button>
    </div>
  );
}

// packages/vue/src/components/Counter.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCathode } from '../useCathode';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

interface Props {
  modelValue: number;
  min?: number;
  max?: number;
  step?: number;
  label?: string;
  format?: (v: number) => string;
  disabled?: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  min: 0,
  max: 100,
  step: 1,
});
const emit = defineEmits<{ 'update:modelValue': [value: number] }>();
const cathode = useCathode();

const canDec = computed(() => !props.disabled && props.modelValue - props.step >= props.min);
const canInc = computed(() => !props.disabled && props.modelValue + props.step <= props.max);
const shown  = computed(() => props.format ? props.format(props.modelValue) : String(props.modelValue));

function fire(dir: -1 | 1) {
  const next = props.modelValue + dir * props.step;
  if (next < props.min || next > props.max) return;
  if (cathode.haptic) haptic('tap');
  if (cathode.sound)  sound('tick', { enabled: true });
  emit('update:modelValue', next);
}
</script>

<template>
  <div class="cathode-counter">
    <button
      type="button"
      class="cathode-counter-btn"
      :data-motion="cathode.motion"
      :disabled="!canDec"
      aria-label="Decrease"
      @click="fire(-1)"
    >−</button>
    <div class="cathode-counter-display">
      <span v-if="props.label" class="cathode-counter-label">{{ props.label }}</span>
      <span class="cathode-counter-value">{{ shown }}</span>
    </div>
    <button
      type="button"
      class="cathode-counter-btn"
      :data-motion="cathode.motion"
      :disabled="!canInc"
      aria-label="Increase"
      @click="fire(1)"
    >+</button>
  </div>
</template>

<style scoped>
button[data-motion='strong']:active:not(:disabled) { transform: scale(0.97); }
button[data-motion='subtle']:active:not(:disabled) { transform: scale(0.99); }
button { transition: transform 80ms cubic-bezier(0.4, 0, 0.2, 1); }
</style>
