// packages/react/src/components/Drawer.tsx
import { useEffect } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import type { ReactNode } from 'react';
import { useCathode } from '../CathodeProvider';

/**
 * Drawer — slide-in panel anchored to the viewport edge. Use for
 * settings, filters, inspector panels — anything that needs room
 * but shouldn't fully cover the underlying content the way Dialog
 * does.
 *
 * Not modal by default (click-outside closes). Pass `modal` to
 * force the user to close via the × or an explicit action.
 */
export interface DrawerProps {
  open: boolean;
  onClose: () => void;
  children: ReactNode;
  title?: string;
  /** Edge to anchor to. Default 'right'. */
  side?: 'left' | 'right' | 'top' | 'bottom';
  /** Panel size — width for left/right, height for top/bottom. Default 360. */
  size?: number;
  /** Prevent click-outside/Escape close. */
  modal?: boolean;
}

export function Drawer({ open, onClose, children, title, side = 'right', size = 360, modal }: DrawerProps) {
  const { motion: motionIntensity } = useCathode();

  // ESC closes (unless modal). Mount only while open to avoid leaks.
  useEffect(() => {
    if (!open || modal) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, modal, onClose]);

  if (typeof document === 'undefined') return null;

  const isHorizontal = side === 'left' || side === 'right';
  const initial = motionIntensity === 'none' ? {} :
    side === 'right'  ? { x:  '100%' } :
    side === 'left'   ? { x: '-100%' } :
    side === 'bottom' ? { y:  '100%' } :
                        { y: '-100%' };
  const animate = motionIntensity === 'none' ? {} : { x: 0, y: 0 };

  return createPortal(
    <AnimatePresence>
      {open ? (
        <motion.div
          className="cathode-drawer-backdrop"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: motionIntensity === 'none' ? 0 : 0.15 }}
          onClick={modal ? undefined : onClose}
        >
          <motion.aside
            className="cathode-drawer"
            data-side={side}
            style={isHorizontal ? { width: size } : { height: size }}
            initial={initial}
            animate={animate}
            exit={initial}
            transition={{ duration: motionIntensity === 'none' ? 0 : 0.2, ease: [0.4, 0, 0.2, 1] }}
            onClick={(e) => e.stopPropagation()}
            role="dialog"
            aria-modal={modal ? 'true' : 'false'}
            aria-label={title}
          >
            {title ? (
              <div className="cathode-drawer-header">
                <span className="cathode-drawer-title">{title}</span>
                <button
                  type="button"
                  className="cathode-drawer-close"
                  onClick={onClose}
                  aria-label="Close"
                >
                  ×
                </button>
              </div>
            ) : null}
            <div className="cathode-drawer-body">{children}</div>
          </motion.aside>
        </motion.div>
      ) : null}
    </AnimatePresence>,
    document.body
  );
}

// packages/vue/src/components/Drawer.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue';

interface Props {
  open: boolean;
  title?: string;
  side?: 'left' | 'right' | 'top' | 'bottom';
  size?: number;
  modal?: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  side: 'right',
  size: 360,
  modal: false,
});
const emit = defineEmits<{ close: [] }>();

function onKey(e: KeyboardEvent) {
  if (!props.open || props.modal) return;
  if (e.key === 'Escape') emit('close');
}
onMounted(() => document.addEventListener('keydown', onKey));
onUnmounted(() => document.removeEventListener('keydown', onKey));

const isHorizontal = computed(() => props.side === 'left' || props.side === 'right');
const panelStyle = computed(() =>
  isHorizontal.value ? { width: `${props.size}px` } : { height: `${props.size}px` },
);

function onBackdrop(e: MouseEvent) {
  if (props.modal) return;
  if (e.target === e.currentTarget) emit('close');
}
</script>

<template>
  <Teleport to="body">
    <Transition :name="`cathode-drawer-${props.side}`">
      <div
        v-if="props.open"
        class="cathode-drawer-backdrop"
        @click="onBackdrop"
      >
        <aside
          class="cathode-drawer"
          :data-side="props.side"
          :style="panelStyle"
          role="dialog"
          :aria-modal="props.modal ? 'true' : 'false'"
          :aria-label="props.title"
          @click.stop
        >
          <div v-if="props.title" class="cathode-drawer-header">
            <span class="cathode-drawer-title">{{ props.title }}</span>
            <button
              type="button"
              class="cathode-drawer-close"
              aria-label="Close"
              @click="emit('close')"
            >×</button>
          </div>
          <div class="cathode-drawer-body">
            <slot />
          </div>
        </aside>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
/* Backdrop fade applies to every side. */
.cathode-drawer-right-enter-active,
.cathode-drawer-right-leave-active,
.cathode-drawer-left-enter-active,
.cathode-drawer-left-leave-active,
.cathode-drawer-top-enter-active,
.cathode-drawer-top-leave-active,
.cathode-drawer-bottom-enter-active,
.cathode-drawer-bottom-leave-active { transition: opacity 150ms ease; }
.cathode-drawer-right-enter-from,
.cathode-drawer-right-leave-to,
.cathode-drawer-left-enter-from,
.cathode-drawer-left-leave-to,
.cathode-drawer-top-enter-from,
.cathode-drawer-top-leave-to,
.cathode-drawer-bottom-enter-from,
.cathode-drawer-bottom-leave-to     { opacity: 0; }

/* Per-side panel slide — simple translate on enter/leave. */
.cathode-drawer-right-enter-active .cathode-drawer,
.cathode-drawer-right-leave-active .cathode-drawer { transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1); }
.cathode-drawer-right-enter-from   .cathode-drawer,
.cathode-drawer-right-leave-to     .cathode-drawer { transform: translateX(100%); }

.cathode-drawer-left-enter-active  .cathode-drawer,
.cathode-drawer-left-leave-active  .cathode-drawer { transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1); }
.cathode-drawer-left-enter-from    .cathode-drawer,
.cathode-drawer-left-leave-to      .cathode-drawer { transform: translateX(-100%); }

.cathode-drawer-top-enter-active   .cathode-drawer,
.cathode-drawer-top-leave-active   .cathode-drawer { transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1); }
.cathode-drawer-top-enter-from     .cathode-drawer,
.cathode-drawer-top-leave-to       .cathode-drawer { transform: translateY(-100%); }

.cathode-drawer-bottom-enter-active .cathode-drawer,
.cathode-drawer-bottom-leave-active .cathode-drawer { transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1); }
.cathode-drawer-bottom-enter-from   .cathode-drawer,
.cathode-drawer-bottom-leave-to     .cathode-drawer { transform: translateY(100%); }
</style>
