// packages/react/src/components/Kbd.tsx
/**
 * Kbd — keyboard shortcut indicator. Each key renders in its own
 * bordered box; keys are joined by a separator (default "+"). Use
 * inline in menu items, hint rows, or anywhere you want to surface a
 * shortcut the user can actually press.
 *
 * Accepts either a string (which is split on "+" or "-") or an array
 * of key names. Arrays are preferred when any key literally contains
 * a "+" (e.g. `['Shift', '+']`).
 */
export interface KbdProps {
  keys: string | ReadonlyArray<string>;
  /** Separator glyph shown between keys. Default "+". */
  separator?: string;
  /** Compact variant — smaller font, tighter padding. */
  size?: 'sm' | 'md';
  className?: string;
}

export function Kbd({
  keys,
  separator = '+',
  size = 'md',
  className,
}: KbdProps) {
  const parts: ReadonlyArray<string> = Array.isArray(keys)
    ? keys
    : (keys as string).split(/\s*[+\-]\s*/).filter(Boolean);

  return (
    <span
      className={['cathode-kbd', className].filter(Boolean).join(' ')}
      data-size={size}
      role="group"
    >
      {parts.map((k: string, i: number) => (
        <span key={i} className="cathode-kbd-group">
          <kbd className="cathode-kbd-key">{k}</kbd>
          {i < parts.length - 1 ? (
            <span className="cathode-kbd-sep" aria-hidden>{separator}</span>
          ) : null}
        </span>
      ))}
    </span>
  );
}

// packages/vue/src/components/Kbd.vue
<script setup lang="ts">
import { computed } from 'vue';

/**
 * Kbd — keyboard shortcut indicator. Accepts a string (split on +/-)
 * or an array of key names. Keys joined by a separator (default "+").
 */
interface Props {
  keys: string | readonly string[];
  separator?: string;
  size?: 'sm' | 'md';
}
const props = withDefaults(defineProps<Props>(), {
  separator: '+',
  size: 'md',
});
const parts = computed<readonly string[]>(() =>
  Array.isArray(props.keys)
    ? (props.keys as readonly string[])
    : (props.keys as string).split(/\s*[+\-]\s*/).filter(Boolean),
);
</script>

<template>
  <span class="cathode-kbd" :data-size="props.size" role="group">
    <span v-for="(k, i) in parts" :key="i" class="cathode-kbd-group">
      <kbd class="cathode-kbd-key">{{ k }}</kbd>
      <span v-if="i < parts.length - 1" class="cathode-kbd-sep" aria-hidden="true">{{ props.separator }}</span>
    </span>
  </span>
</template>
