// packages/react/src/components/PixelBar.tsx
import { useCathode } from '../CathodeProvider';

/**
 * Discrete-cell level meter — a horizontal row of small squares that
 * fill left-to-right proportional to `level` in [0, 1].
 *
 * The motion profile runs a light cascade fill when `level` changes
 * meaningfully (≥ one cell). Disabled under `motion="none"` or
 * `prefers-reduced-motion: reduce`.
 *
 * Styled by base.css; the active fill color comes from the
 * `--cathode-pixelbar-fill` CSS custom property so apps can theme
 * individual bars without a prop cascade. Default falls back to
 * `--cathode-color-tx`.
 */
export interface PixelBarProps {
  /** 0…1 — clamped inside. */
  level: number;
  /** Number of discrete cells. Default 24. */
  cells?: number;
  /** Explicit fill color override; otherwise the CSS var wins. */
  fill?: string;
  /** Bar height in px — each cell is square. Default 6. */
  cellSize?: number;
  /** Accessible name for the progress indicator. Defaults to "Level". */
  'aria-label'?: string;
  /** ID of an element labelling this bar; takes precedence over aria-label. */
  'aria-labelledby'?: string;
  className?: string;
}

export function PixelBar({
  level,
  cells = 24,
  fill,
  cellSize = 6,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  className,
}: PixelBarProps) {
  useCathode(); // subscribe so motion intensity changes trigger re-render
  const clamped = Math.max(0, Math.min(1, level));
  const active = Math.round(clamped * cells);

  return (
    <div
      className={['cathode-pixelbar', className].filter(Boolean).join(' ')}
      style={{
        // Override the CSS var locally when an explicit `fill` was passed.
        ...(fill ? ({ ['--cathode-pixelbar-fill']: fill } as React.CSSProperties) : {}),
      }}
      role="progressbar"
      aria-valuemin={0}
      aria-valuemax={1}
      aria-valuenow={clamped}
      aria-label={ariaLabelledBy ? undefined : (ariaLabel ?? 'Level')}
      aria-labelledby={ariaLabelledBy}
    >
      {Array.from({ length: cells }, (_, i) => (
        <span
          key={i}
          className="cathode-pixelbar-cell"
          data-lit={i < active ? 'true' : 'false'}
          style={{ width: cellSize, height: cellSize }}
        />
      ))}
    </div>
  );
}

// packages/vue/src/components/PixelBar.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

/** Discrete-cell horizontal level meter, 0..1 clamped. */
interface Props {
  level: number;
  cells?: number;
  fill?: string;
  cellSize?: number;
  ariaLabel?: string;
  ariaLabelledby?: string;
}
const props = withDefaults(defineProps<Props>(), { cells: 24, cellSize: 6 });

const clamped = computed(() => Math.max(0, Math.min(1, props.level)));
const active  = computed(() => Math.round(clamped.value * props.cells));
const rootStyle = computed<CSSProperties>(() =>
  props.fill ? ({ ['--cathode-pixelbar-fill' as any]: props.fill }) : ({}),
);
</script>

<template>
  <div
    class="cathode-pixelbar"
    :style="rootStyle"
    role="progressbar"
    aria-valuemin="0"
    aria-valuemax="1"
    :aria-valuenow="clamped"
    :aria-label="props.ariaLabelledby ? undefined : (props.ariaLabel ?? 'Level')"
    :aria-labelledby="props.ariaLabelledby"
  >
    <span
      v-for="i in props.cells"
      :key="i"
      class="cathode-pixelbar-cell"
      :data-lit="(i - 1) < active ? 'true' : 'false'"
      :style="{ width: `${props.cellSize}px`, height: `${props.cellSize}px` }"
    />
  </div>
</template>
