// packages/react/src/components/Popover.tsx
import { Children, cloneElement, isValidElement, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import type { ReactElement, ReactNode } from 'react';

/**
 * Popover — anchored floating panel, shown on click of the trigger.
 * Closes on outside click or Escape. Use for richer content than
 * Tooltip (which is hover-triggered, text-only) and lighter than
 * Dialog (which is modal and portaled).
 *
 * The panel is rendered via `createPortal(document.body)` and
 * positioned with `position: fixed` using the trigger's viewport
 * rect, so ancestor `overflow: hidden` / `transform` can't clip it.
 * Recomputes position on window resize + scroll.
 */
export interface PopoverProps {
  trigger: ReactNode;
  children: ReactNode;
  /** Start open. Uncontrolled fallback; controlled consumers use `open` + `onOpenChange`. */
  defaultOpen?: boolean;
  /** Controlled open state. */
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  align?: 'start' | 'end';
  className?: string;
}

export function Popover({
  trigger,
  children,
  defaultOpen = false,
  open: controlledOpen,
  onOpenChange,
  align = 'start',
  className,
}: PopoverProps) {
  const [internal, setInternal] = useState(defaultOpen);
  const open = controlledOpen ?? internal;
  const rootRef = useRef<HTMLDivElement | null>(null);
  const panelRef = useRef<HTMLDivElement | null>(null);
  const [pos, setPos] = useState<{ top: number; left: number } | null>(null);

  const setOpen = (v: boolean) => {
    if (controlledOpen === undefined) setInternal(v);
    onOpenChange?.(v);
  };

  useLayoutEffect(() => {
    if (!open || !rootRef.current) return;
    const place = () => {
      const r = rootRef.current!.getBoundingClientRect();
      const panelW = panelRef.current?.offsetWidth ?? 200;
      setPos({
        top: r.bottom + 6,
        left: align === 'end' ? r.right - panelW : r.left,
      });
    };
    place();
    window.addEventListener('resize', place);
    window.addEventListener('scroll', place, true);
    return () => {
      window.removeEventListener('resize', place);
      window.removeEventListener('scroll', place, true);
    };
  }, [open, align]);

  useEffect(() => {
    if (!open) return;
    const onDoc = (e: MouseEvent) => {
      const t = e.target as Node;
      if (rootRef.current?.contains(t)) return;
      if (panelRef.current?.contains(t)) return;
      setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('mousedown', onDoc);
      document.removeEventListener('keydown', onKey);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // ARIA belongs on the actual interactive trigger element — clone
  // the child to inject onClick + aria-haspopup + aria-expanded.
  const triggerEl: ReactNode = isValidElement(trigger)
    ? cloneElement(Children.only(trigger) as ReactElement<any>, {
        onClick: (...args: unknown[]) => {
          (trigger as ReactElement<any>).props.onClick?.(...args);
          setOpen(!open);
        },
        'aria-haspopup': 'dialog',
        'aria-expanded': open,
      })
    : trigger;

  const panel = open && pos ? (
    <div
      ref={panelRef}
      className="cathode-popover-panel"
      role="dialog"
      data-align={align}
      style={{ position: 'fixed', top: pos.top, left: pos.left }}
    >
      {children}
    </div>
  ) : null;

  return (
    <div ref={rootRef} className={['cathode-popover', className].filter(Boolean).join(' ')}>
      {triggerEl}
      {typeof document !== 'undefined' && panel ? createPortal(panel, document.body) : null}
    </div>
  );
}

// packages/vue/src/components/Popover.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick, watch } from 'vue';

interface Props {
  /** v-model:open */
  open?: boolean;
  defaultOpen?: boolean;
  align?: 'start' | 'end';
}
// `open: undefined` is intentional — without it, Vue auto-coerces
// missing boolean props to `false`, making it impossible to tell
// "uncontrolled mode" apart from "controlled with open=false". The
// explicit undefined default preserves the tri-state we need.
const props = withDefaults(defineProps<Props>(), {
  open: undefined,
  align: 'start',
  defaultOpen: false,
});
const emit = defineEmits<{ 'update:open': [v: boolean] }>();

const internal = ref(props.defaultOpen);
const isOpen = computed(() => props.open ?? internal.value);

function setOpen(v: boolean) {
  if (props.open === undefined) internal.value = v;
  emit('update:open', v);
}

const rootEl  = ref<HTMLDivElement | null>(null);
const panelEl = ref<HTMLDivElement | null>(null);
const pos     = ref<{ top: number; left: number } | null>(null);

async function place() {
  if (!isOpen.value || !rootEl.value) return;
  await nextTick();
  const r = rootEl.value.getBoundingClientRect();
  const panelW = panelEl.value?.offsetWidth ?? 200;
  pos.value = { top: r.bottom + 6, left: props.align === 'end' ? r.right - panelW : r.left };
}

function toggle() {
  const next = !isOpen.value;
  setOpen(next);
  // place() also fires via the `watch(isOpen)` below, but calling it
  // here keeps the trigger-click path identical to Menu's model.
  if (next) place();
}

// Controlled consumers (v-model:open, or :open="true") bypass toggle()
// and set isOpen directly. Without this watch, place() never runs and
// the panel's v-if="isOpen && pos" never satisfies — the panel stays
// invisible even though isOpen is true. We can't use `immediate: true`
// here because template refs aren't bound until after the first render;
// place() reads rootEl.value and would no-op. The onMounted hook below
// handles the "open at mount time" case once refs are guaranteed live.
watch(isOpen, (v) => {
  if (v) place();
  else   pos.value = null;
});

function onDocMouse(e: MouseEvent) {
  if (!isOpen.value) return;
  const t = e.target as Node;
  if (rootEl.value?.contains(t)) return;
  if (panelEl.value?.contains(t)) return;
  setOpen(false);
}
function onKey(e: KeyboardEvent) {
  if (isOpen.value && e.key === 'Escape') setOpen(false);
}
function onScroll() { place(); }

onMounted(() => {
  document.addEventListener('mousedown', onDocMouse);
  document.addEventListener('keydown', onKey);
  window.addEventListener('resize', place);
  window.addEventListener('scroll', onScroll, true);
  // If a consumer mounted the Popover with :open="true" from the
  // first render, the watch above didn't see a state transition —
  // we have to kick off place() ourselves here, now that refs are
  // live, so the panel actually appears.
  if (isOpen.value) place();
});
onUnmounted(() => {
  document.removeEventListener('mousedown', onDocMouse);
  document.removeEventListener('keydown', onKey);
  window.removeEventListener('resize', place);
  window.removeEventListener('scroll', onScroll, true);
});
</script>

<template>
  <div ref="rootEl" class="cathode-popover">
    <span
      role="button"
      :aria-haspopup="'dialog'"
      :aria-expanded="isOpen"
      @click="toggle"
    ><slot name="trigger" /></span>
    <Teleport to="body">
      <div
        v-if="isOpen && pos"
        ref="panelEl"
        class="cathode-popover-panel"
        role="dialog"
        :data-align="props.align"
        :style="{ position: 'fixed', top: `${pos.top}px`, left: `${pos.left}px` }"
      >
        <slot />
      </div>
    </Teleport>
  </div>
</template>
