// packages/react/src/components/Skeleton.tsx
/**
 * Skeleton — placeholder block for content that's still loading. A
 * moving shimmer indicates "something is coming here". Compose
 * multiple Skeletons to mirror the final layout so the page doesn't
 * jump when data arrives.
 *
 * No rounded corners — Cathode prefers pixel squares. Caller sets
 * dimensions via `width`/`height` or CSS.
 */
export interface SkeletonProps {
  width?: number | string;
  height?: number | string;
  /** Visual variant — `text` is short + inline-y; `block` fills its container. */
  variant?: 'text' | 'block';
  className?: string;
}

export function Skeleton({ width, height, variant = 'block', className }: SkeletonProps) {
  const style: React.CSSProperties = {
    width: typeof width === 'number' ? `${width}px` : width,
    height: typeof height === 'number' ? `${height}px` : height,
  };
  return (
    <span
      className={['cathode-skeleton', className].filter(Boolean).join(' ')}
      data-variant={variant}
      style={style}
      aria-hidden
    />
  );
}

// packages/vue/src/components/Skeleton.vue
<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';

/** Placeholder shimmer while content loads. */
interface Props {
  width?: number | string;
  height?: number | string;
  variant?: 'text' | 'block';
}
const props = withDefaults(defineProps<Props>(), { variant: 'block' });
const style = computed<CSSProperties>(() => ({
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
}));
</script>

<template>
  <span class="cathode-skeleton" :data-variant="props.variant" :style="style" aria-hidden="true" />
</template>
