// packages/react/src/components/Table.tsx
import type { ReactNode } from 'react';

/**
 * Table — terminal-style tabular display. Column headers uppercase,
 * monospace values, subtle row dividers. Controlled sort: the table
 * emits a sort-change event; the consumer passes a sorted `rows`.
 * Keeps the component decoupled from data semantics — sorting a
 * string column vs. a number column vs. a date column is the app's
 * concern, not Cathode's.
 *
 * Row click is optional. When set, rows render as `<tr tabIndex=0>`
 * with a pointer cursor and a hover highlight.
 */
export interface TableColumn<T> {
  /** Key into each row. Also the sort identifier. */
  key: keyof T & string;
  /** Header text, rendered uppercase. */
  header: string;
  align?: 'left' | 'right' | 'center';
  /** Fixed column width (e.g. "120px", "20%"). Otherwise auto. */
  width?: string | number;
  /** Custom cell renderer; defaults to `String(row[key])`. */
  render?: (row: T, rowIndex: number) => ReactNode;
  sortable?: boolean;
}

export interface TableProps<T extends Record<string, unknown>> {
  columns: ReadonlyArray<TableColumn<T>>;
  rows: ReadonlyArray<T>;
  sortBy?: keyof T & string;
  sortDir?: 'asc' | 'desc';
  onSortChange?: (key: keyof T & string, dir: 'asc' | 'desc') => void;
  onRowClick?: (row: T, rowIndex: number) => void;
  /** Shown above the table for screen readers; visible if `showCaption`. */
  caption?: string;
  showCaption?: boolean;
  /** Rendered when `rows` is empty. Default "No data." */
  emptyText?: string;
  className?: string;
}

export function Table<T extends Record<string, unknown>>({
  columns,
  rows,
  sortBy,
  sortDir = 'asc',
  onSortChange,
  onRowClick,
  caption,
  showCaption,
  emptyText = 'NO DATA',
  className,
}: TableProps<T>) {
  const handleHeaderClick = (col: TableColumn<T>) => {
    if (!col.sortable || !onSortChange) return;
    const nextDir: 'asc' | 'desc' =
      sortBy === col.key && sortDir === 'asc' ? 'desc' : 'asc';
    onSortChange(col.key, nextDir);
  };

  return (
    <table className={['cathode-table', className].filter(Boolean).join(' ')}>
      {caption ? (
        <caption
          className="cathode-table-caption"
          data-visible={showCaption ? 'true' : 'false'}
        >
          {caption}
        </caption>
      ) : null}
      <thead>
        <tr>
          {columns.map((col) => {
            const isSorted = sortBy === col.key;
            const thProps: React.ThHTMLAttributes<HTMLTableCellElement> = {
              className: 'cathode-table-th',
              scope: 'col',
              style: {
                textAlign: col.align ?? 'left',
                width: typeof col.width === 'number' ? `${col.width}px` : col.width,
              },
              'aria-sort': isSorted ? (sortDir === 'asc' ? 'ascending' : 'descending') : undefined,
            };
            return (
              <th key={col.key} {...thProps}>
                {col.sortable ? (
                  <button
                    type="button"
                    className="cathode-table-sort"
                    onClick={() => handleHeaderClick(col)}
                    data-sorted={isSorted ? 'true' : 'false'}
                  >
                    {col.header}
                    {isSorted ? (
                      <span aria-hidden className="cathode-table-sort-arrow">
                        {sortDir === 'asc' ? '▴' : '▾'}
                      </span>
                    ) : null}
                  </button>
                ) : (
                  col.header
                )}
              </th>
            );
          })}
        </tr>
      </thead>
      <tbody>
        {rows.length === 0 ? (
          <tr>
            <td className="cathode-table-empty" colSpan={columns.length}>
              {emptyText}
            </td>
          </tr>
        ) : (
          rows.map((row, i) => {
            const clickable = !!onRowClick;
            return (
              <tr
                key={i}
                className="cathode-table-row"
                data-clickable={clickable ? 'true' : 'false'}
                tabIndex={clickable ? 0 : undefined}
                onClick={clickable ? () => onRowClick!(row, i) : undefined}
                onKeyDown={
                  clickable
                    ? (e) => {
                        if (e.key === 'Enter' || e.key === ' ') {
                          e.preventDefault();
                          onRowClick!(row, i);
                        }
                      }
                    : undefined
                }
              >
                {columns.map((col) => (
                  <td
                    key={col.key}
                    className="cathode-table-td"
                    style={{ textAlign: col.align ?? 'left' }}
                  >
                    {col.render ? col.render(row, i) : String(row[col.key] ?? '')}
                  </td>
                ))}
              </tr>
            );
          })
        )}
      </tbody>
    </table>
  );
}

// packages/vue/src/components/Table.vue
<script setup lang="ts" generic="T extends Record<string, unknown>">
import type { CSSProperties } from 'vue';

export interface TableColumn<T> {
  key: keyof T & string;
  header: string;
  align?: 'left' | 'right' | 'center';
  width?: string | number;
  sortable?: boolean;
}

// Export the props interface so vue-tsc's generated declaration can
// reference it without the "private name" TS4082 error that shows up
// when the generic `T` escapes an unexported interface.
export interface TableProps<T extends Record<string, unknown>> {
  columns: readonly TableColumn<T>[];
  rows: readonly T[];
  sortBy?: keyof T & string;
  sortDir?: 'asc' | 'desc';
  emptyText?: string;
  caption?: string;
  showCaption?: boolean;
  rowClickable?: boolean;
}
const props = withDefaults(defineProps<TableProps<T>>(), {
  sortDir: 'asc',
  emptyText: 'NO DATA',
});
const emit = defineEmits<{
  sortChange: [key: keyof T & string, dir: 'asc' | 'desc'];
  rowClick:   [row: T, index: number];
}>();

function headerClick(col: TableColumn<T>) {
  if (!col.sortable) return;
  const nextDir = props.sortBy === col.key && props.sortDir === 'asc' ? 'desc' : 'asc';
  emit('sortChange', col.key, nextDir);
}
function cellStyle(col: TableColumn<T>): CSSProperties {
  return { textAlign: col.align ?? 'left' };
}
function headerStyle(col: TableColumn<T>): CSSProperties {
  return {
    textAlign: col.align ?? 'left',
    width: typeof col.width === 'number' ? `${col.width}px` : col.width,
  };
}
function ariaSort(col: TableColumn<T>): 'ascending' | 'descending' | undefined {
  if (props.sortBy !== col.key) return undefined;
  return props.sortDir === 'asc' ? 'ascending' : 'descending';
}
function onRowClick(row: T, i: number) {
  if (props.rowClickable) emit('rowClick', row, i);
}
function onRowKey(row: T, i: number, e: KeyboardEvent) {
  if (!props.rowClickable) return;
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault();
    emit('rowClick', row, i);
  }
}
</script>

<template>
  <table class="cathode-table">
    <caption
      v-if="props.caption"
      class="cathode-table-caption"
      :data-visible="props.showCaption ? 'true' : 'false'"
    >{{ props.caption }}</caption>
    <thead>
      <tr>
        <th
          v-for="col in props.columns"
          :key="col.key"
          class="cathode-table-th"
          scope="col"
          :style="headerStyle(col)"
          :aria-sort="ariaSort(col)"
        >
          <button
            v-if="col.sortable"
            type="button"
            class="cathode-table-sort"
            :data-sorted="props.sortBy === col.key ? 'true' : 'false'"
            @click="headerClick(col)"
          >
            {{ col.header }}
            <span
              v-if="props.sortBy === col.key"
              aria-hidden="true"
              class="cathode-table-sort-arrow"
            >{{ props.sortDir === 'asc' ? '▴' : '▾' }}</span>
          </button>
          <template v-else>{{ col.header }}</template>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-if="props.rows.length === 0">
        <td class="cathode-table-empty" :colspan="props.columns.length">{{ props.emptyText }}</td>
      </tr>
      <tr
        v-else
        v-for="(row, i) in props.rows"
        :key="i"
        class="cathode-table-row"
        :data-clickable="props.rowClickable ? 'true' : 'false'"
        :tabindex="props.rowClickable ? 0 : undefined"
        @click="onRowClick(row, i)"
        @keydown="(e) => onRowKey(row, i, e)"
      >
        <td
          v-for="col in props.columns"
          :key="col.key"
          class="cathode-table-td"
          :style="cellStyle(col)"
        >
          <slot :name="`cell-${col.key}`" :row="row" :index="i" :value="row[col.key]">
            {{ row[col.key] ?? '' }}
          </slot>
        </td>
      </tr>
    </tbody>
  </table>
</template>
