// packages/react/src/components/TextArea.tsx
/**
 * TextArea — multi-line monospace text input. Shares the TextField
 * chrome but renders <textarea> instead of <input>. Resize handle is
 * disabled by default; callers control sizing via `rows` or CSS so
 * the terminal aesthetic isn't broken by the native corner-grip.
 */
export interface TextAreaProps {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  disabled?: boolean;
  rows?: number;
  /** Show a character count at the bottom-right. Default off. */
  maxLength?: number;
  /** Opt out of the default `resize: none`. */
  resizable?: boolean;
  /** Font weight of the typed text. Default 'regular'. */
  weight?: 'regular' | 'bold';
  className?: string;
  'aria-label'?: string;
  'aria-labelledby'?: string;
  'aria-describedby'?: string;
}

export function TextArea({
  value,
  onChange,
  placeholder,
  disabled,
  rows = 4,
  maxLength,
  resizable,
  weight = 'regular',
  className,
  'aria-label': ariaLabel,
  'aria-labelledby': ariaLabelledBy,
  'aria-describedby': ariaDescribedBy,
}: TextAreaProps) {
  return (
    <div className={['cathode-textarea', className].filter(Boolean).join(' ')} data-weight={weight}>
      <textarea
        className="cathode-textarea-native"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        disabled={disabled}
        rows={rows}
        maxLength={maxLength}
        aria-label={ariaLabelledBy ? undefined : ariaLabel}
        aria-labelledby={ariaLabelledBy}
        aria-describedby={ariaDescribedBy}
        spellCheck={false}
        style={resizable ? undefined : { resize: 'none' }}
      />
      {maxLength ? (
        <div className="cathode-textarea-counter" aria-hidden>
          {value.length} / {maxLength}
        </div>
      ) : null}
    </div>
  );
}

// packages/vue/src/components/TextArea.vue
<script setup lang="ts">
import { inject, computed } from 'vue';
import { FORM_FIELD_KEY } from './formFieldContext';

interface Props {
  modelValue: string;
  placeholder?: string;
  disabled?: boolean;
  rows?: number;
  maxLength?: number;
  resizable?: boolean;
  weight?: 'regular' | 'bold';
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaDescribedby?: string;
}
const props = withDefaults(defineProps<Props>(), { rows: 4, weight: 'regular' });
const emit = defineEmits<{ 'update:modelValue': [v: string] }>();
const formField = inject(FORM_FIELD_KEY, undefined);
const resizeStyle = computed(() => (props.resizable ? undefined : { resize: 'none' as const }));
</script>

<template>
  <div class="cathode-textarea" :data-weight="props.weight">
    <textarea
      class="cathode-textarea-native"
      :value="props.modelValue"
      :placeholder="props.placeholder"
      :disabled="props.disabled"
      :rows="props.rows"
      :maxlength="props.maxLength"
      :aria-label="(props.ariaLabelledby || formField?.labelledBy) ? undefined : props.ariaLabel"
      :aria-labelledby="props.ariaLabelledby ?? formField?.labelledBy"
      :aria-describedby="props.ariaDescribedby ?? formField?.describedBy"
      spellcheck="false"
      :style="resizeStyle"
      @input="(e) => emit('update:modelValue', (e.target as HTMLTextAreaElement).value)"
    />
    <div v-if="props.maxLength" class="cathode-textarea-counter" aria-hidden="true">
      {{ props.modelValue.length }} / {{ props.maxLength }}
    </div>
  </div>
</template>
