// packages/react/src/components/Toggle.tsx
import { motion } from 'framer-motion';
import { useCathode } from '../CathodeProvider';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

/**
 * Binary on/off switch in the Cathode terminal language.
 *
 * Square-cornered track (no pill radius — that breaks the aesthetic).
 * The knob slides from left to right; track fills with the accent
 * color when on. Tap anywhere on the track to toggle. Feedback is a
 * `tick` sound + `tap` haptic by default.
 */
export interface ToggleProps {
  value: boolean;
  onChange: (v: boolean) => void;
  label?: string;
  disabled?: boolean;
  /** Accent color when on. Defaults to `success`. */
  accent?: 'success' | 'info' | 'warning' | 'danger' | 'accent' | 'amber' | 'pink' | 'purple' | 'teal';
  className?: string;
  'aria-label'?: string;
}

export function Toggle({
  value,
  onChange,
  label,
  disabled,
  accent = 'success',
  className,
  'aria-label': ariaLabel,
}: ToggleProps) {
  const { motion: motionIntensity, haptic: hapticOn, sound: soundOn } = useCathode();

  const handleClick = () => {
    if (disabled) return;
    if (hapticOn) haptic('tap');
    if (soundOn) sound('tick', { enabled: true });
    onChange(!value);
  };

  const duration = motionIntensity === 'none' ? 0 : 0.12;

  return (
    <label
      className={['cathode-toggle', disabled ? 'is-disabled' : '', className].filter(Boolean).join(' ')}
    >
      <button
        type="button"
        role="switch"
        aria-checked={value}
        aria-label={ariaLabel ?? label}
        disabled={disabled}
        className="cathode-toggle-track"
        data-on={value ? 'true' : 'false'}
        data-accent={accent}
        onClick={handleClick}
      >
        <motion.span
          className="cathode-toggle-knob"
          animate={{ x: value ? 16 : 0 }}
          transition={{ duration, ease: 'easeOut' }}
        />
      </button>
      {label ? <span className="cathode-toggle-label">{label}</span> : null}
    </label>
  );
}

// packages/vue/src/components/Toggle.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useCathode } from '../useCathode';
import { haptic } from '../feedback/haptic';
import { sound } from '../feedback/sound';

interface Props {
  /** v-model value */
  modelValue: boolean;
  label?: string;
  disabled?: boolean;
  accent?: 'success' | 'info' | 'warning' | 'danger' | 'accent' | 'amber' | 'pink' | 'purple' | 'teal';
  ariaLabel?: string;
}
const props = withDefaults(defineProps<Props>(), {
  accent: 'success',
});
const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

const cathode = useCathode();

function handleClick() {
  if (props.disabled) return;
  if (cathode.haptic) haptic('tap');
  if (cathode.sound) sound('tick', { enabled: true });
  emit('update:modelValue', !props.modelValue);
}

const knobStyle = computed(() => ({
  transform: `translateX(${props.modelValue ? 16 : 0}px)`,
  transition: cathode.motion === 'none' ? 'none' : 'transform 120ms ease-out',
}));
</script>

<template>
  <label
    class="cathode-toggle"
    :class="{ 'is-disabled': props.disabled }"
    :aria-disabled="props.disabled || undefined"
  >
    <button
      type="button"
      role="switch"
      :aria-checked="props.modelValue"
      :aria-label="props.ariaLabel ?? props.label"
      :disabled="props.disabled"
      class="cathode-toggle-track"
      :data-on="props.modelValue ? 'true' : 'false'"
      :data-accent="props.accent"
      @click="handleClick"
    >
      <span class="cathode-toggle-knob" :style="knobStyle" />
    </button>
    <span v-if="props.label" class="cathode-toggle-label">{{ props.label }}</span>
  </label>
</template>
